config/routes.rb
Rails.application.routes.draw do
  root "page#home"
  resources :consultations

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/consultation.rb
class Consultation < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/consultations_controller.rb
class ConsultationsController < ApplicationController
  before_action :set_consultation, only: %i[ show edit update destroy ]

  # GET /consultations or /consultations.json
  def index
    @consultations = Consultation.all
  end

  # GET /consultations/1 or /consultations/1.json
  def show
  end

  # GET /consultations/new
  def new
    @consultation = Consultation.new
  end

  # GET /consultations/1/edit
  def edit
  end

  # POST /consultations or /consultations.json
  def create
    @consultation = Consultation.new(consultation_params)

    respond_to do |format|
      if @consultation.save
        format.html { redirect_to consultation_url(@consultation), notice: "Consultation was successfully created." }
        format.json { render :show, status: :created, location: @consultation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @consultation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consultations/1 or /consultations/1.json
  def update
    respond_to do |format|
      if @consultation.update(consultation_params)
        format.html { redirect_to consultation_url(@consultation), notice: "Consultation was successfully updated." }
        format.json { render :show, status: :ok, location: @consultation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @consultation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultations/1 or /consultations/1.json
  def destroy
    @consultation.destroy

    respond_to do |format|
      format.html { redirect_to consultations_url, notice: "Consultation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultation
      @consultation = Consultation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def consultation_params
      params.require(:consultation).permit(:title, :description, :start_time, :end_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/views/consultations/_consultation.html.erb
<div id="<%= dom_id consultation %>">
  <p>
    <strong>Title:</strong>
    <%= consultation.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= consultation.description %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= consultation.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= consultation.end_time %>
  </p>

</div>

app/views/consultations/_form.html.erb
<%= form_with(model: consultation) do |form| %>
  <% if consultation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(consultation.errors.count, "error") %> prohibited this consultation from being saved:</h2>

      <ul>
        <% consultation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.datetime_field :start_time %>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block" %>
    <%= form.datetime_field :end_time %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/consultations/edit.html.erb
<h1>Editing consultation</h1>

<%= render "form", consultation: @consultation %>

<br>

<div>
  <%= link_to "Show this consultation", @consultation %> |
  <%= link_to "Back to consultations", consultations_path %>
</div>

app/views/consultations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Consultations</h1>

<div id="consultations">
  <% @consultations.each do |consultation| %>
    <%= render consultation %>
    <p>
      <%= link_to "Show this consultation", consultation %>
    </p>
  <% end %>
</div>

<%= link_to "New consultation", new_consultation_path %>

app/views/consultations/new.html.erb
<h1>New consultation</h1>

<%= render "form", consultation: @consultation %>

<br>

<div>
  <%= link_to "Back to consultations", consultations_path %>
</div>

app/views/consultations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @consultation %>

<div>
  <%= link_to "Edit this consultation", edit_consultation_path(@consultation) %> |
  <%= link_to "Back to consultations", consultations_path %>

  <%= button_to "Destroy this consultation", @consultation, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalendarRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>